imports:
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: parameters.yml }
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

# Framework configuration
framework:
    secret: '%secret%'
    http_method_override: true
    default_locale: '%default_locale%'
    trusted_hosts: ~
    # fragments configuration
    fragments:
        enabled: false
    # esi configuration
    esi:
        enabled: false
    # csrf protection configuration
    csrf_protection:
        enabled: true
    # assets configuration
    assets:
        json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'
    # translator configuration
    translator:
        enabled: true
        fallbacks: ['%default_locale%']
        logging: "%kernel.debug%"
        paths: ["%kernel.project_dir%/translations"]
    # router configuration
    router:
        resource: '%kernel.project_dir%/config/routing.yml'
        # 'true' is the preferred configuration in development mode, while
        # 'false' or 'null' might be preferred in production
        strict_requirements:  true
    # form configuration
    form:
        enabled: true
        csrf_protection:
            enabled: true
    # session configuration
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    # templating configuration
    templating:
        form:
            resources:
                - FrameworkBundle:Form
        engines:
            - twig
    # validation configuration
    validation:
        enabled: true
        enable_annotations: true
    # serializer configuration
    serializer:
       enabled: true
       enable_annotations: true
    # php errors configuration
    php_errors:
        log: true

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                DATE_FORMAT: ServiceBundle\DoctrineExtensions\DateFormat

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - "form/layout.html.twig"
# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# FOSUserBundle Configuration
fos_user:
    service:
        mailer: fos_user.mailer.twig_swift
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: ServiceBundle\Entity\UserManagment\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    resetting:
        email:
            template:   emails/password_resetting.email.twig
    profile:
        form:
            type: ServiceBundle\Form\User\ProfileFormType
    registration:
        confirmation:
            enabled:    true # change to true for required email confirmation
            template:   emails/registration_mail.email.twig
# KnpPaginator Configuration
knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: 'KnpPaginator/Pagination/sliding.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template

# VichUploaderBundle Configuration
vich_uploader:
    db_driver: orm
    mappings:
        user_image:
            uri_prefix:         /images/user
            upload_destination: '%kernel.root_dir%/web/images/user'
            namer: vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        portfolio_image:
            uri_prefix:         /images/portfolio
            upload_destination: '%kernel.root_dir%/web/images/portfolio'
            namer: vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        intrest_image:
            uri_prefix:         /images/intrest
            upload_destination: '%kernel.root_dir%/web/images/intrest'
            namer: vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

# liip imagine Configuration
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/web
                cache_prefix: media/cache

    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/web/
    filter_sets:
        # name our filter set "my_thumb_filter"
        thumbnail_50_x_50:
            filters:
                # use and setup the "relative_resize" filter
                relative_resize:

                    # given 50x40px, output 75x60px using "heighten" option
                    heighten: 50
        # name our filter set "my_thumb_filter"
        thumbnail_250_x_250:
            filters:
                # use and setup the "thumbnail" filter
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [250, 250]
                    # crop the input image, if required
                    mode: outbound
        thumbnail_150_x_150:
            filters:
                # use and setup the "thumbnail" filter
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [150, 150]
                    # crop the input image, if required
                    mode: outbound

# KnpSnappyBundle Configuration
knp_snappy:
    temporary_folder: "%kernel.cache_dir%/snappy"
    pdf:
        enabled:    true
        binary:     %kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
        options:    []
    image:
        enabled:    true
        binary:     %kernel.project_dir%/vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64 #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
        options:    []

# HWIOAuthBundle Configuration
# hwi_oauth:
#     # list of names of the firewalls in which this bundle is active, this setting MUST be set
#     firewall_names: [secured_area]
#     resource_owners:
#         any_name:
#             type:                facebook
#             client_id:           <client_id>
#             client_secret:       <client_secret>
#             options:
#                 csrf: true
