imports:
    - { resource: config_dev.yml }
    - { resource: parameters_dev.yml }

# Framework Configuration
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

# web profiler Configuration
web_profiler:
    toolbar: false
    intercept_redirects: false

# swiftmailer Configuration
swiftmailer:
    disable_delivery: true
