imports:
    - { resource: config.yml }
    - { resource: parameters_dev.yml }
# Framework Configuration
framework:
    router:
        resource: '%kernel.project_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

# Web profiler Configuration
web_profiler:
    toolbar: true
    intercept_redirects: false

# monolog Configuration
monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        firephp:
            type: firephp
            level: info
        chromephp:
            type: chromephp
            level: info

# swiftmailer Configuration
swiftmailer:
    transport: gmail
    username: '%mailer_user%'
    password: '%mailer_password%'

# jms translation Configuration
jms_translation:
    configs:
        app:
            dirs: ["%kernel.root_dir%/templates", "%kernel.root_dir%/src"]
            output_dir: "%kernel.root_dir%/translations"
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
