# Put all the parameters used in your dev environment
parameters:
    # Doctrine Configuration
    database_host: 127.0.0.1
    database_port: null
    database_name: service_db
    database_user: service_user
    database_password: 123456
    # Swiftmailer Configuration
    mailer_transport: smtp
    mailer_host: smtp.gmail.com
    mailer_user: ramisfari22@gmail.com
    mailer_password: ramisfari123
